# Few-shot dataset
nClsEpisode: 5 # number of categories in each episode
nSupport: 1 # number of samples per category in the support set
nQuery: 15 # number of samples per category in the query set
dataset: 'miniImageNet' # choices = ['miniImageNet', 'Cifar']

# Network
nStep: 3 
nbIter: 50000 
architecture: 'WRN_28_10'  # choices = ['WRN_28_10', 'Conv64_4']
batchSize: 8 # number of episodes in each batch

# Optimizer
lr: 0.001 
weightDecay: 0.0005 #5e-4 
momentum: 0.9 

# Training details
expName: miniImageNet
resumeFeatPth: './ckpts/Mini-ImageNet/netFeatBest64.653.pth'
ckptPth: '' #'cache/miniImageNet_1shot_100/outputs_73.924/netSIBBest73.924.pth'
outDir: ''
logDir: ''
coeffGrad: 0

# Testing
nEpisode: 2000
